In [1]:
import numpy

In [2]:
def cal_pop_fitness(equation_inputs, pop):

    # Calcular el valor de aptitud de cada solución en la población actual.
    # La función fitness calcula la suma de productos entre cada entrada y su peso correspondiente.
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    # Seleccionar a los mejores individuos de la generación actual como padres para producir la descendencia de la próxima generación.
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # El punto en el que se produce el cruce entre dos padres. Generalmente está en el centro.
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Índice del primer padre en mesclarse.
        parent1_idx = k%parents.shape[0]
        # Índice del segundo padre en mesclarse..
        parent2_idx = (k+1)%parents.shape[0]
        # La primera mitad de los genes de la nueva descendencia se tomará del primer padre.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # A la nueva descendencia se le tomará la segunda mitad de sus genes del segundo padre.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover, num_mutations=1):
    mutations_counter = numpy.uint8(offspring_crossover.shape[1] / num_mutations)
    # La mutación cambia una cantidad de genes según lo definido por el argumento num_mutations. Los cambios son aleatorios.
    for idx in range(offspring_crossover.shape[0]):
        gene_idx = mutations_counter - 1
        for mutation_num in range(num_mutations):
            # El valor aleatorio que se agregará al gen.
            random_value = numpy.random.uniform(-1.0, 1.0, 1)
            offspring_crossover[idx, gene_idx] = offspring_crossover[idx, gene_idx] + random_value
            gene_idx = gene_idx + mutations_counter
    return offspring_crossover



$y = w_1*x_1 +w_2*x_2+w_3*x_3+w_4*x_4+w_5*x_5+w_6*x_6$


In [3]:
# Entradas de la ecuación.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

In [4]:
# Número de pesos que buscamos optimizar.
num_weights = 6

In [5]:
sol_per_pop = 20
num_parents_mating = 10

In [6]:
#Mating pool size=Tamaño del grupo de mescla
#Population size=tamaño de la poblacion Tamaño de la poblacion

# Definición del tamaño de la población.
pop_size = (sol_per_pop, num_weights) # La población tendrá el cromosoma sol_per_pop donde cada cromosoma tiene genes num_weights.
#Creando la población inicial.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

[[ 1.57388023  2.73364755 -0.42064198 -0.25466895  3.64200757  1.32243121]
 [ 3.04634053 -3.64034852 -0.9020057   3.96681654  3.75837202 -3.21032491]
 [-3.23823656 -3.04782178  0.2453176   0.9857272   0.03781884  2.00210827]
 [ 0.39768525  0.72221228 -1.21843794  0.51810457 -1.99246468  3.78321802]
 [ 2.88349149  3.72528581  0.33022223 -0.86397553 -2.00396984 -3.03242401]
 [-0.40144562  0.91659918 -0.06859023  2.20135388  2.8342462  -3.0711435 ]
 [ 1.23034309 -2.79546456  2.26626592  2.45894631 -1.90425601  1.05227929]
 [-3.4460069  -3.37280457 -1.79987824  3.04352385 -3.60427613  0.24576178]
 [-3.94457667  2.05596109  1.60237708  1.78299186  1.74439954  2.96066305]
 [-3.1090425   2.8129473  -3.49915688 -2.96855166 -3.50120152 -3.91573635]
 [-2.67315779 -2.27945962  1.12873275  3.62007121 -1.29678235  1.20266854]
 [-2.26552009 -2.61505851  1.04812199 -1.79419953  0.32942918 -3.13752517]
 [ 0.69684644 -1.43932443 -1.68309988  0.85901532  0.98689162  0.6599171 ]
 [ 3.5901064   3.0919376 

In [10]:
num_generations = 100
for generation in range(num_generations):
    print("Generacion : ", generation)
    # Medir la aptitud de cada cromosoma en la población.
    fitness = cal_pop_fitness(equation_inputs, new_population)

    # Seleccionar a los mejores padres de la población para el apareamiento.
    parents = select_mating_pool(new_population, fitness,
                                      num_parents_mating)

    # Generando la próxima generación usando crossover.
    offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Agregar algunas variaciones a la descendencia usando mutación.
    offspring_mutation = mutation(offspring_crossover)

    # Creando la nueva población basada en padres e hijos.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    # El mejor resultado en la iteración actual.
    print("Mejor resultado : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

Generacion :  0
Mejor resultado :  262.3332905222709
Generacion :  1
Mejor resultado :  266.58243008516547
Generacion :  2
Mejor resultado :  267.11499306642065
Generacion :  3
Mejor resultado :  270.6358106838218
Generacion :  4
Mejor resultado :  273.1564524930118
Generacion :  5
Mejor resultado :  273.1564524930118
Generacion :  6
Mejor resultado :  276.08564206857386
Generacion :  7
Mejor resultado :  279.4101622960913
Generacion :  8
Mejor resultado :  281.0254247208427
Generacion :  9
Mejor resultado :  282.07026885427365
Generacion :  10
Mejor resultado :  283.58979402529974
Generacion :  11
Mejor resultado :  287.46380643206015
Generacion :  12
Mejor resultado :  291.6638253012907
Generacion :  13
Mejor resultado :  292.0513316480458
Generacion :  14
Mejor resultado :  295.8999289750466
Generacion :  15
Mejor resultado :  295.8999289750466
Generacion :  16
Mejor resultado :  299.20645560306576
Generacion :  17
Mejor resultado :  299.20645560306576
Generacion :  18
Mejor resulta

In [11]:
# Obteniendo la mejor solución después de iterar y terminar todas las generaciones.
#Al principio, se calcula la aptitud para cada solución en la generación final.
fitness = cal_pop_fitness(equation_inputs, new_population)
# Luego devuelve el índice de esa solución correspondiente a la mejor aptitud.
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Mejor solucion : ", new_population[best_match_idx, :])
print("Mejor solución fitness : ", fitness[best_match_idx])

Mejor solucion :  [[[ 3.82949771e+00 -1.70876797e+00 -1.59083357e-02  3.04352385e+00
   -3.60427613e+00 -7.89482366e+01]]]
Mejor solución fitness :  [444.60121641]
